### ISSUE TITLE
Regression tests fail because it can't load phdf

### ISSUE THREAD

**Issue by BenWibking** [parthenon-hpc-lab/athenapk#33]
Inside a virtualenv with Python 3.9.6:
```
*****************************************************************
Preparing Test Case Step 39
*****************************************************************

*****************************************************************
Running Driver
*****************************************************************

Command to execute driver
/mnt/home/wibkingb/athenapk/build/bin/athenaPK -i /mnt/home/wibkingb/athenapk/inputs/sod.in parthenon/mesh/nx1=64 parthenon/meshblock/nx1=64 parthenon/time/integrator=rk3 hydro/reconstruction=wenoz parthenon/mesh/nghost=3 hydro/riemann=hllc parthenon/output0/id=39 problem/sod/rho_l=1.4 problem/sod/pres_l=1.0 problem/sod/u_l=0.1 problem/sod/rho_r=1.0 problem/sod/u_r=0.1 problem/sod/pres_r=1.0 problem/sod/x_discont=0.5 parthenon/time/tlim=2.0 parthenon/output0/dt=2.0
Running with coverage
False
*****************************************************************
Analysing Driver Output
*****************************************************************

Couldn't find module to read Parthenon hdf5 files.
Traceback (most recent call last):
  File "/mnt/home/wibkingb/athenapk/external/parthenon/tst/regression/run_test.py", line 204, in <module>
    main(**vars(args))
  File "/mnt/home/wibkingb/athenapk/external/parthenon/tst/regression/run_test.py", line 93, in main
    raise TestError("Test " + test_manager.test + " failed")
__main__.TestError: Test riemann_hydro failed
```

**Comment by BenWibking** [comment]
This appears to go away once the dependencies are satisfied: https://github.com/parthenon-hpc-lab/athenapk/issues/32
